python inference_final_mag_cplx_grappa.py \
  --model_pth /home/lin/Research/denoise/Restormer/weights/net_g_220000_best_morenoise.pth \
  --mri_list /home/lin/Downloads/grappa_b1k/paths_b1k.txt \
  --mri_format grappa \
  --mri_key img_coil_single_dir \
  --use_noise \
  --noise_mat /home/lin/Downloads/grappa_b1k/pf1_noise_v4.mat \
  --noise_key image \
  --noise_format grappa \
  --output_folder ./results_grappa_b1k_mask \
  --brain_mask /home/lin/Downloads/grappa_b1k/grappa_mask.nii
